spring:
  cloud:
    gateway:
      routes:
        - id: rapport-service
          uri: http://localhost:8022
          predicates:
            - Path=/rapport/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**

  application:
    name: GATEWAY-SERVICE
